import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spotifyFont = localFont({
  src: [
    {
      path: "../../public/fonts/spotify/Spotify-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/spotify/Spotify-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-spotify",
  display: "swap",
  adjustFontFallback: "Times New Roman",
});

const vscodeFont = localFont({
  src: [
    {
      path: "../../public/fonts/vscode/CONSOLA.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/vscode/CONSOLAB.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-vscode",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spotifyFont.variable} ${vscodeFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
